/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'disastersPrevented' : bigint,
  'redCommands' : bigint,
  'greenCommands' : bigint,
  'rejectedCommands' : bigint,
  'blockedCommands' : bigint,
  'approvedCommands' : bigint,
  'yellowCommands' : bigint,
  'activeAgents' : bigint,
  'totalCommands' : bigint,
  'requestsPerMinute' : number,
}
export interface ApprovalResult { 'message' : string, 'success' : boolean }
export interface BlastRadius {
  'estimatedFiles' : bigint,
  'severity' : string,
  'estimatedRows' : bigint,
}
export interface CommandLog {
  'id' : string,
  'status' : CommandStatus,
  'approverId' : [] | [string],
  'approverReason' : [] | [string],
  'agentId' : string,
  'command' : string,
  'timestamp' : Timestamp,
  'blastRadius' : [] | [BlastRadius],
  'riskLevel' : RiskLevel,
  'commandType' : string,
}
export type CommandStatus = { 'pending' : null } |
  { 'blocked' : null } |
  { 'allowed' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface InterceptResult {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'blocked' : null } |
    { 'allowed' : null },
  'blastRadius' : [] | [BlastRadius],
  'riskLevel' : RiskLevel,
  'reason' : string,
}
export interface LogFilter {
  'status' : [] | [string],
  'agentId' : [] | [string],
  'limit' : [] | [bigint],
  'riskLevel' : [] | [string],
}
export type RiskLevel = { 'red' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface SystemHealth {
  'pendingApprovals' : bigint,
  'uptime' : bigint,
  'activeAgents' : bigint,
  'requestsPerMinute' : number,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'reviewer' : null };
export interface _SERVICE {
  'approve' : ActorMethod<
    [string, boolean, string, [] | [string]],
    ApprovalResult
  >,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getLogs' : ActorMethod<[[] | [LogFilter]], Array<CommandLog>>,
  'getMyRole' : ActorMethod<[], [] | [UserRole]>,
  'getPendingApprovals' : ActorMethod<[], Array<CommandLog>>,
  'getSystemHealth' : ActorMethod<[], SystemHealth>,
  'intercept' : ActorMethod<[string, string, string], InterceptResult>,
  'setUserRole' : ActorMethod<[string, UserRole], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];