/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApprovalResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const Analytics = IDL.Record({
  'disastersPrevented' : IDL.Nat,
  'redCommands' : IDL.Nat,
  'greenCommands' : IDL.Nat,
  'rejectedCommands' : IDL.Nat,
  'blockedCommands' : IDL.Nat,
  'approvedCommands' : IDL.Nat,
  'yellowCommands' : IDL.Nat,
  'activeAgents' : IDL.Nat,
  'totalCommands' : IDL.Nat,
  'requestsPerMinute' : IDL.Float64,
});
export const LogFilter = IDL.Record({
  'status' : IDL.Opt(IDL.Text),
  'agentId' : IDL.Opt(IDL.Text),
  'limit' : IDL.Opt(IDL.Nat),
  'riskLevel' : IDL.Opt(IDL.Text),
});
export const CommandStatus = IDL.Variant({
  'pending' : IDL.Null,
  'blocked' : IDL.Null,
  'allowed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const BlastRadius = IDL.Record({
  'estimatedFiles' : IDL.Nat,
  'severity' : IDL.Text,
  'estimatedRows' : IDL.Nat,
});
export const RiskLevel = IDL.Variant({
  'red' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const CommandLog = IDL.Record({
  'id' : IDL.Text,
  'status' : CommandStatus,
  'approverId' : IDL.Opt(IDL.Text),
  'approverReason' : IDL.Opt(IDL.Text),
  'agentId' : IDL.Text,
  'command' : IDL.Text,
  'timestamp' : Timestamp,
  'blastRadius' : IDL.Opt(BlastRadius),
  'riskLevel' : RiskLevel,
  'commandType' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'reviewer' : IDL.Null,
});
export const SystemHealth = IDL.Record({
  'pendingApprovals' : IDL.Nat,
  'uptime' : IDL.Int,
  'activeAgents' : IDL.Nat,
  'requestsPerMinute' : IDL.Float64,
});
export const InterceptResult = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'blocked' : IDL.Null,
    'allowed' : IDL.Null,
  }),
  'blastRadius' : IDL.Opt(BlastRadius),
  'riskLevel' : RiskLevel,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  'approve' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text, IDL.Opt(IDL.Text)],
      [ApprovalResult],
      [],
    ),
  'getAnalytics' : IDL.Func([], [Analytics], ['query']),
  'getLogs' : IDL.Func([IDL.Opt(LogFilter)], [IDL.Vec(CommandLog)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
  'getPendingApprovals' : IDL.Func([], [IDL.Vec(CommandLog)], ['query']),
  'getSystemHealth' : IDL.Func([], [SystemHealth], ['query']),
  'intercept' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [InterceptResult], []),
  'setUserRole' : IDL.Func([IDL.Text, UserRole], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApprovalResult = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const Analytics = IDL.Record({
    'disastersPrevented' : IDL.Nat,
    'redCommands' : IDL.Nat,
    'greenCommands' : IDL.Nat,
    'rejectedCommands' : IDL.Nat,
    'blockedCommands' : IDL.Nat,
    'approvedCommands' : IDL.Nat,
    'yellowCommands' : IDL.Nat,
    'activeAgents' : IDL.Nat,
    'totalCommands' : IDL.Nat,
    'requestsPerMinute' : IDL.Float64,
  });
  const LogFilter = IDL.Record({
    'status' : IDL.Opt(IDL.Text),
    'agentId' : IDL.Opt(IDL.Text),
    'limit' : IDL.Opt(IDL.Nat),
    'riskLevel' : IDL.Opt(IDL.Text),
  });
  const CommandStatus = IDL.Variant({
    'pending' : IDL.Null,
    'blocked' : IDL.Null,
    'allowed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const BlastRadius = IDL.Record({
    'estimatedFiles' : IDL.Nat,
    'severity' : IDL.Text,
    'estimatedRows' : IDL.Nat,
  });
  const RiskLevel = IDL.Variant({
    'red' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const CommandLog = IDL.Record({
    'id' : IDL.Text,
    'status' : CommandStatus,
    'approverId' : IDL.Opt(IDL.Text),
    'approverReason' : IDL.Opt(IDL.Text),
    'agentId' : IDL.Text,
    'command' : IDL.Text,
    'timestamp' : Timestamp,
    'blastRadius' : IDL.Opt(BlastRadius),
    'riskLevel' : RiskLevel,
    'commandType' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'reviewer' : IDL.Null });
  const SystemHealth = IDL.Record({
    'pendingApprovals' : IDL.Nat,
    'uptime' : IDL.Int,
    'activeAgents' : IDL.Nat,
    'requestsPerMinute' : IDL.Float64,
  });
  const InterceptResult = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'blocked' : IDL.Null,
      'allowed' : IDL.Null,
    }),
    'blastRadius' : IDL.Opt(BlastRadius),
    'riskLevel' : RiskLevel,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'approve' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text, IDL.Opt(IDL.Text)],
        [ApprovalResult],
        [],
      ),
    'getAnalytics' : IDL.Func([], [Analytics], ['query']),
    'getLogs' : IDL.Func(
        [IDL.Opt(LogFilter)],
        [IDL.Vec(CommandLog)],
        ['query'],
      ),
    'getMyRole' : IDL.Func([], [IDL.Opt(UserRole)], ['query']),
    'getPendingApprovals' : IDL.Func([], [IDL.Vec(CommandLog)], ['query']),
    'getSystemHealth' : IDL.Func([], [SystemHealth], ['query']),
    'intercept' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [InterceptResult],
        [],
      ),
    'setUserRole' : IDL.Func([IDL.Text, UserRole], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };