/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlastRadius {
    estimatedFiles: bigint;
    severity: string;
    estimatedRows: bigint;
}
export type Timestamp = bigint;
export interface CommandLog {
    id: string;
    status: CommandStatus;
    approverId?: string;
    approverReason?: string;
    agentId: string;
    command: string;
    timestamp: Timestamp;
    blastRadius?: BlastRadius;
    riskLevel: RiskLevel;
    commandType: string;
}
export interface Analytics {
    disastersPrevented: bigint;
    redCommands: bigint;
    greenCommands: bigint;
    rejectedCommands: bigint;
    blockedCommands: bigint;
    approvedCommands: bigint;
    yellowCommands: bigint;
    activeAgents: bigint;
    totalCommands: bigint;
    requestsPerMinute: number;
}
export interface SystemHealth {
    pendingApprovals: bigint;
    uptime: bigint;
    activeAgents: bigint;
    requestsPerMinute: number;
}
export interface LogFilter {
    status?: string;
    agentId?: string;
    limit?: bigint;
    riskLevel?: string;
}
export interface InterceptResult {
    id: string;
    status: Variant_pending_blocked_allowed;
    blastRadius?: BlastRadius;
    riskLevel: RiskLevel;
    reason: string;
}
export interface ApprovalResult {
    message: string;
    success: boolean;
}
export enum CommandStatus {
    pending = "pending",
    blocked = "blocked",
    allowed = "allowed",
    approved = "approved",
    rejected = "rejected"
}
export enum RiskLevel {
    red = "red",
    green = "green",
    yellow = "yellow"
}
export enum UserRole {
    admin = "admin",
    reviewer = "reviewer"
}
export enum Variant_pending_blocked_allowed {
    pending = "pending",
    blocked = "blocked",
    allowed = "allowed"
}
export interface backendInterface {
    approve(commandId: string, decision: boolean, callerId: string, reason: string | null): Promise<ApprovalResult>;
    getAnalytics(): Promise<Analytics>;
    getLogs(filter: LogFilter | null): Promise<Array<CommandLog>>;
    getMyRole(): Promise<UserRole | null>;
    getPendingApprovals(): Promise<Array<CommandLog>>;
    getSystemHealth(): Promise<SystemHealth>;
    intercept(command: string, agentId: string, commandType: string): Promise<InterceptResult>;
    setUserRole(userId: string, role: UserRole): Promise<boolean>;
}
import type { BlastRadius as _BlastRadius, CommandLog as _CommandLog, CommandStatus as _CommandStatus, InterceptResult as _InterceptResult, LogFilter as _LogFilter, RiskLevel as _RiskLevel, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async approve(arg0: string, arg1: boolean, arg2: string, arg3: string | null): Promise<ApprovalResult> {
        if (this.processError) {
            try {
                const result = await this.actor.approve(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approve(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getLogs(arg0: LogFilter | null): Promise<Array<CommandLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogs(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogs(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingApprovals(): Promise<Array<CommandLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingApprovals();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingApprovals();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemHealth(): Promise<SystemHealth> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemHealth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemHealth();
            return result;
        }
    }
    async intercept(arg0: string, arg1: string, arg2: string): Promise<InterceptResult> {
        if (this.processError) {
            try {
                const result = await this.actor.intercept(arg0, arg1, arg2);
                return from_candid_InterceptResult_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.intercept(arg0, arg1, arg2);
            return from_candid_InterceptResult_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: string, arg1: UserRole): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CommandLog_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommandLog): CommandLog {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CommandStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommandStatus): CommandStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_InterceptResult_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterceptResult): InterceptResult {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_RiskLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskLevel): RiskLevel {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlastRadius]): BlastRadius | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        blocked: null;
    } | {
        allowed: null;
    };
    blastRadius: [] | [_BlastRadius];
    riskLevel: _RiskLevel;
    reason: string;
}): {
    id: string;
    status: Variant_pending_blocked_allowed;
    blastRadius?: BlastRadius;
    riskLevel: RiskLevel;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n19(_uploadFile, _downloadFile, value.status),
        blastRadius: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.blastRadius)),
        riskLevel: from_candid_RiskLevel_n12(_uploadFile, _downloadFile, value.riskLevel),
        reason: value.reason
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _CommandStatus;
    approverId: [] | [string];
    approverReason: [] | [string];
    agentId: string;
    command: string;
    timestamp: _Timestamp;
    blastRadius: [] | [_BlastRadius];
    riskLevel: _RiskLevel;
    commandType: string;
}): {
    id: string;
    status: CommandStatus;
    approverId?: string;
    approverReason?: string;
    agentId: string;
    command: string;
    timestamp: Timestamp;
    blastRadius?: BlastRadius;
    riskLevel: RiskLevel;
    commandType: string;
} {
    return {
        id: value.id,
        status: from_candid_CommandStatus_n8(_uploadFile, _downloadFile, value.status),
        approverId: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.approverId)),
        approverReason: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.approverReason)),
        agentId: value.agentId,
        command: value.command,
        timestamp: value.timestamp,
        blastRadius: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.blastRadius)),
        riskLevel: from_candid_RiskLevel_n12(_uploadFile, _downloadFile, value.riskLevel),
        commandType: value.commandType
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    green: null;
} | {
    yellow: null;
}): RiskLevel {
    return "red" in value ? RiskLevel.red : "green" in value ? RiskLevel.green : "yellow" in value ? RiskLevel.yellow : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    reviewer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "reviewer" in value ? UserRole.reviewer : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    blocked: null;
} | {
    allowed: null;
}): Variant_pending_blocked_allowed {
    return "pending" in value ? Variant_pending_blocked_allowed.pending : "blocked" in value ? Variant_pending_blocked_allowed.blocked : "allowed" in value ? Variant_pending_blocked_allowed.allowed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    blocked: null;
} | {
    allowed: null;
} | {
    approved: null;
} | {
    rejected: null;
}): CommandStatus {
    return "pending" in value ? CommandStatus.pending : "blocked" in value ? CommandStatus.blocked : "allowed" in value ? CommandStatus.allowed : "approved" in value ? CommandStatus.approved : "rejected" in value ? CommandStatus.rejected : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommandLog>): Array<CommandLog> {
    return value.map((x)=>from_candid_CommandLog_n6(_uploadFile, _downloadFile, x));
}
function to_candid_LogFilter_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogFilter): _LogFilter {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LogFilter | null): [] | [_LogFilter] {
    return value === null ? candid_none() : candid_some(to_candid_LogFilter_n3(_uploadFile, _downloadFile, value));
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: string;
    agentId?: string;
    limit?: bigint;
    riskLevel?: string;
}): {
    status: [] | [string];
    agentId: [] | [string];
    limit: [] | [bigint];
    riskLevel: [] | [string];
} {
    return {
        status: value.status ? candid_some(value.status) : candid_none(),
        agentId: value.agentId ? candid_some(value.agentId) : candid_none(),
        limit: value.limit ? candid_some(value.limit) : candid_none(),
        riskLevel: value.riskLevel ? candid_some(value.riskLevel) : candid_none()
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    reviewer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.reviewer ? {
        reviewer: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
